---
target_server: all
logsdir: /db/exp/ansible/bkp_reports
dbname: all
reportdays: 10
mailto: nvnckmr@gmail.com
tgtenv: purescale
#reportsserver: ftwlxtstt003.iss.bnr.com
reportsserver: 192.168.1.19
reportsdir: /tmp/bkp_reports