---
  - stat: path='/tmp/prepatch.complete'
    register: prepatchcomplete
  - import_tasks: prepatch.yml
    when: not prepatchcomplete.stat.exists
  - file: path='/tmp/prepatch.complete' state='touch' mode='0777'
    tags: prepatch

  - stat: path='/tmp/installfp.complete'
    register: installfpcomplete
  - import_tasks: installfp.yml
    when: 
      - installupdate == "install" or installupdate == "install_update"
      - not installfpcomplete.stat.exists
  - file: path='/tmp/installfp.complete' state='touch' mode='0777'
    tags: install