  - block:
      - debug: msg="Start - Prebackups"
        run_once: true

      - stat: path='/tmp/prepatch.complete'
        register: prepatchcomplete

      - import_tasks: prepatch.yml

      - file: path='/tmp/prepatch.complete' state='touch' mode='0777'

      - debug: msg="End - Prebackups"
        run_once: true
    when: not prepatchcomplete.stat.exists
    tags: prepatch

  - block:
      - debug: msg="Start - StopDB2"
        run_once: true

      - stat: path='/tmp/stopdb2.complete'
        register: stopdb2complete

      - import_tasks: stopdb2.yml

      - file: path='/tmp/stopdb2.complete' state='touch' mode='0777'

      - debug: msg="End - StopDB2"
        run_once: true
    when: not stopdb2complete.stat.exists
    tags: stopdb2

  - block:
      - debug: msg="Start - InstallFixpack"
        run_once: true

      - stat: path='/tmp/installfp.complete'
        register: installfpcomplete

      - import_tasks: installfp.yml
        when: installupdate == "install_update"

      - file: path='/tmp/installfp.complete' state='touch' mode='0777'

      - debug: msg="End - InstallFixpack"
        run_once: true
    when: not installfpcomplete.stat.exists
    tags: install

  - block:
      - debug: msg="Start - iUpdate"
        run_once: true

      - stat: path='/tmp/updateinc.complete'
        register: updateinccomplete

      - import_tasks: updateinc.yml

      - file: path='/tmp/updateinc.complete' state='touch' mode='0777'

      - debug: msg="End - iUpdate"
        run_once: true
    when: not updateinccomplete.stat.exists
    tags: iupdate

  - block:
      - debug: msg="Start - StartDB2"
        run_once: true

      - stat: path='/tmp/startdb2.complete'
        register: startdb2complete

      - import_tasks: startdb2.yml

      - file: path='/tmp/startdb2.complete' state='touch' mode='0777'

      - debug: msg="End - StartDB2"
        run_once: true
    when: not startdb2complete.stat.exists
    tags: startdb2

  - block:
      - debug: msg="Start - PostBackups"
        run_once: true

      - stat: path='/tmp/postpatch.complete'
        register: postpatchcomplete

      - import_tasks: postpatch.yml

      - file: path='/tmp/postpatch.complete' state='touch' mode='0777'

      - debug: msg="End - PostBackups"
        run_once: true
    when: not postpatchcomplete.stat.exists
    tags: postpatch